### ISSUE TITLE
Segments- Field option is greyed unable to find state option.

### ISSUE THREAD

**Issue by sehrish777** [MicrosoftLearning/MB-260T00-Customer-Data-Platform-Specialty#1]
# Module: 4
#### Step: 3

Field option is greyed unable to find state option. 
![image](https://user-images.githubusercontent.com/52242119/155044884-2a798e7a-b88c-40f4-a05d-74d495c5414d.png)

**Comment by sehrish777** [comment]
This link is required at the start of Mod 2,3,4 and 5. New users face issues in finding the link at the start of labs.  

Sign-into Customer Insights at https://home.ci.ai.dynamics.com/

**Comment by anjenni** [comment]
Thanks for raising this issue @sehrish777, this is very helpful! We're investigating the greyed out issue - it may be a product bug.

I did add the CI home link to the start of all the labs. Thanks so much for that suggestion!
