### ISSUE TITLE
Issue with Dynamics 365 classic Web App (Module 6)

### ISSUE THREAD

**Issue by sehrish777** [MicrosoftLearning/MB-260T00-Customer-Data-Platform-Specialty#2]
# Module: 6
#### Step:  1 to 5

Description of issue
Dynamics 365 classic Web App does not open. 
Either this is an update to the UI that it is not found. Can I get help in troubleshooting this?

**Comment by anjenni** [comment]
Hi @sehrish777, thanks so much for opening this issue. Could this potentially be an issue with your popup blcoker?
