### ISSUE TITLE
Matching conditions section in Customer Insights portal - Doesn't match guide

### ISSUE THREAD

**Issue by LewisGoDeploy** [MicrosoftLearning/MB-260T00-Customer-Data-Platform-Specialty#24]
# Module: 3
#### Step: 1

Description of issue
In this task: "Task 2 - Specify Match Order" you are first asked to "click Match in the top menu on the page" of the "matching conditions" section. This button isn't present and this part of the guide doesn't match up with the customer insights portal. I have tried to continue without this part but the steps don't make sense. 

![image](https://user-images.githubusercontent.com/114931569/216608183-c03cdb6f-3115-4554-9d0b-88b29d2fcd00.png)

**Comment by LewisGoDeploy** [comment]
Any chance I could get an update on this please? We have customers who are unable to follow the guides successfully in a lab environment due to this problem.

**Comment by anjenni** [comment]
Hi Lewis! Thanks for bringing this to our attention and for following up. The steps in Lab 3.1 Task 2 were updated - the buttons changed a bit, and now you can just use the arrows to set the primary and secondary sources. You should be able to move through the lab now. Let me know if anything else comes up.

Thank you!
