### ISSUE TITLE
Match rules and conditions - Portal doesn't match steps 

### ISSUE THREAD

**Issue by LewisGoDeploy** [MicrosoftLearning/MB-260T00-Customer-Data-Platform-Specialty#25]
#### Step: 6

Description of issue
Portal doesn't match up steps, this is going to be the case for multiple sections of MB-260.

In the mention lab, task and step: There is no Save or Run button. After following the previous steps, this is what you are left with: 

![image](https://user-images.githubusercontent.com/114931569/221536409-4632cda9-3ebe-4398-9195-80ea94952fef.png)

**Comment by ephiax20** [comment]
This is resolved in #27

**Comment by anjenni** [comment]
Hi Lewis, this is fixed. Thanks again. Closing issue.
