### ISSUE TITLE
Lab 6.2 - Steps don't match Dynamics portal

### ISSUE THREAD

**Issue by LewisGoDeploy** [MicrosoftLearning/MB-260T00-Customer-Data-Platform-Specialty#30]
#### Step: 1

Description of issue

- Guide steps no longer match up with Customer Insights/Dynamics portal.
- Step 1 states "Click Data >Unify and then Map" - there is no Map option. After this you are required to click "Edit Fields" under "Entities" which is not present.

A lot of lab 6.2 needs reviewing.
- There is no longer a "Match" tab, or a "Merge" tab (task 3)

Appreciate if this could be reviewed and updated. I have worked around some issues in previous labs but sometimes the guides are so far from the current portal it is hard to.

Thank you

**Comment by anjenni** [comment]
Thanks Lewis! Simon (our tester) is moving through and should get to this lab shortly. Will close out when fixed. Thanks.

**Comment by LewisGoDeploy** [comment]
@anjenni That's great news! Thank you very much.
