### ISSUE TITLE
LAB not functioning properly

### ISSUE THREAD

**Issue by Shahhista** [MicrosoftLearning/MB-260T00-Customer-Data-Platform-Specialty#37]
# Module: 2
#### Step: 

Description of issue:

Data is not getting Ingested and it is taking too long for the data ingestion and after a time period of one day it is showing the status as failed.The Status is just showing as refreshing from 9 Hours
![Screenshot 2023-12-05 121803](https://github.com/MicrosoftLearning/MB-260T00-Customer-Data-Platform-Specialty/assets/114824595/546521c4-761a-4db4-a374-4b2b882eedad)

**Comment by SkillableKarl** [comment]
We also saw a very long period of time for data to be ingested.  In the case of our full end-to-end QA, he commented yesterday while still QA'ing: 

*"...While importing the data into Customer Insights – Data, using the Dataverse connector, the data refreshing has been 'refreshing' for over 5 hours....this has been a hurdle throughout this lab. Multiple tasks within the lab require the student to wait 30-60 minutes for data to refresh."*

Note that today our QA'er rechecked and validated that the 'refresh' did finally complete successfully, however as seen in this issue report - it does appear there can be some serious delay and/or failures in the Dynamics site backend that can lead to very long delays/fails in some cases.

This may not be something that can be truly resolved except by the MSFT site backend, but it may be worthwhile to place notes in key locations in these Instructions to warn of potential delays.

**Comment by ephiax20** [comment]
Unable to replicate this, it was taking in the range of ~10 mins to ingest data when I tested this recently.
